version: '3'
services:
    app:
        build: .
        container_name: azapfy-api-app
        volumes:
            - .:/var/www
        networks:
            - app-network

    nginx:
        build: docker/nginx
        container_name: azapfy-api-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app
networks:
    app-network:
        driver: bridge
